server:
  port: 8082
spring:
  application:
    name: provider-payment8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url:  jdbc:mysql://192.168.20.245:3306/jiazw?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: testdascom

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.60.251:7001/eureka/
