server:
  port: 80
spring:
  application:
    name: orderService
  zipkin:
    base-url: http://192.168.20.244:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.60.251:7001/eureka/

