server:
  port: 8083
spring:
  application:
    name: provider-nacospayment8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url:  jdbc:mysql://192.168.20.245:3306/jiazw?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: testdascom


  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.244:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
