server:
  port: 8082
spring:
  application:
    name: provider-conpayment8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url:  jdbc:mysql://192.168.20.245:3306/jiazw?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: testdascom
  cloud:
    consul:
      host: 192.168.60.251
      port: 8500
      discovery:
        service-name: ${spring.application.name}

mybatis:
  mapper-locations: classpath:mapper/*.xml
