server:
  port: 80
spring:
  application:
    name: conOrderService
  cloud:
    consul:
      host: 192.168.60.251
      port: 8500
      discovery:
        service-name: ${spring.application.name}



